apiVersion: v1
kind: Service
metadata:
  name: cosy-template-service
spec:
  selector:
    app: cosy-template-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
